### PR TITLE
Updated to work with Electra Release 1

### PR DESCRIPTION
**Pull request by FaZeIlLuMiNaTi**
Electra requires entitlements to be added. I've added the required entitlements as entitlements.xml and modified the Makefile to run ldid against these specified entitlements. The current version is hosted on my repo for testing purposes and works for me on iOS 11.0.3, Electra Release 1.0.1.

I don't have a 32-bit device with a compatible jailbreak to test, but theoretically, the app should be compiled correctly and run on 32-bit platforms.

This update should be ready to push to BigBoss.

### CODE REVIEW

**Comment by lululombard** [comment]
Wonderful job ! Just noticed, the `.deb` is missing, could you check ? Thanks !

**Comment by FaZeIlLuMiNaTi** [comment]
It's located in [packages](https://github.com/lululombard/CertRemainTime/tree/master/packages). Sorry, I forgot to move it.

**Comment by lululombard** [comment]
Oh okay ! The update has been pushed to BigBoss, should be live in 48 hours max !

**Comment by FaZeIlLuMiNaTi** [comment]
Thanks!

**Pull request merged**
